### ISSUE TITLE
Data interpolation unexpectedly behaves like a vector

### ISSUE THREAD

**Issue by gaurav-arya** [SciML/DataInterpolations.jl#240]
The behaviour is defined here:

https://github.com/SciML/DataInterpolations.jl/blob/0641b6929f564ca0ded6ea50015e8ac02ee79861/src/DataInterpolations.jl#L5-L16

This can lead to surprising results beyond just the getindex. For example, running `copy` on a data interpolation produces a vector with the u's and t's concatenated.

**Comment by ChrisRackauckas** [comment]
It was due to how it would interact with ModelingToolkit in the past for controls applications. There are many instances where you want to treat the interpolation as a vector of parameters to fit. But yeah the ecosystem grew around this and now there's better ways of specifying a control function to fit using MTK and this is an interface oddity that remains. Probably should be removed.
