### ISSUE TITLE
Second derivatives of interpolations

### ISSUE THREAD

**Issue by bclyons12** [SciML/DataInterpolations.jl#96]
I know how to use DataInterpolations to get the derivative of an interpolation, like below, but is there anyway to get the second derivative?
```
using DataInterpolations
using DataInterpolations: derivative
N = 10
x = collect(range(0.0, 1.0, length=N))
y = x.^2
yi = CubicSpline(y,x)
println(yi(0.5))             # 0.5^2 = 0.25
println(derivative(yi, 0.5)) # 2*0.5 = 1.00
```

**Comment by ChrisRackauckas** [comment]
Not right now. It would be something good and not too hard to add though.

**Comment by cnrrobertson** [comment]
Would it be reasonable to try implementing derivative functions which return the respective `AbstractInterpolation` object rather than the derivative evaluated at a point? This would allow you to get an arbitrary number of derivatives by just reapplying the function. `Polynomials.jl` has this functionality [here](https://juliamath.github.io/Polynomials.jl/stable/reference/#Polynomials.derivative).

It seems like this should be somewhat straightforward for most of the methods, except possibly the BSplines? I'm not as familiar with them. I could take a stab at it if you're open to the idea.

**Comment by bclyons12** [comment]
Most interpolations would only have continuous derivatives up to a certain order, so you'd need to agree on how to handle discontinuous derivatives.

**Comment by sathvikbhagavan** [comment]
Now we have support for second order derivatives, @ChrisRackauckas, can this be closed?
