### ISSUE TITLE
Tutorial/demonstration includes Loess and GaussianProcess examples

### ISSUE THREAD

**Issue by jjstickel** [SciML/DataInterpolations.jl#97]
The Readme links to 

https://htmlpreview.github.io/?https://github.com/PumasAI/DataInterpolations.jl/blob/v2.0.0/example/DataInterpolations.html

which includes examples for Loess and GaussianProcess interpolations, but it seems those features have been removed from the package.

Also, may I ask why they have been removed? I am interested to contribute data smoothing/interpolation by Tikhonov regularization (aka ridge regression) and thought this might be a good place to include it. But that seems less likely if Loess and GP are out. Have the moved to another package, or are they simply done using the parent packages? I personally think it would be nice to collect the different interpolating and smoothing methods together with a common interface, and thought this might be a good place.

**Comment by andreasnoack** [comment]
Thanks for reporting this. The html needs to be updated to reflect the current functionality. We had to remove the Loess functionality because the implementation wasn't correct and we didn't have the bandwidth to fix it. It can return once somebody gets the time to write a correct implementation. We had to drop the GaussianProcesses support because the package had a lot of dependencies and had insufficient releases which caused too many version conflicts for us.

**Comment by ChrisRackauckas** [comment]
Yeah, it was correctness and dependency issues. I'd be willing to review related contributions: it would be nice to have those kinds of things (under the condition they are correct of course 💀)

**Comment by jjstickel** [comment]
Got it, thanks for the reply. I'll get working soon on a fork of this repo to add regularization smoothing. As a preview, I hope to reimplement what is in [scikit-datasmooth](https://github.com/jjstickel/scikit-datasmooth) as described by [Stickel, 2010](http://dx.doi.org/10.1016/j.compchemeng.2009.10.007). It looks like I can leverage the backend solvers of [RegularizationTools.jl](https://github.com/mdpetters/RegularizationTools.jl).

**Comment by sathvikbhagavan** [comment]
Can this be closed as we don't have Loess and GPs here anymore?
